Incrementle merkle Tree (Dynamic Depth Feature for Binary Merkle Tree)
privacy-scaling-explorations/zk-kit.noir pull request #9
Opened 2024-07-31 12:23 UTC by YashBit

## Important:

1. Creating a simple PR for just a feedback loop, code not ready yet. Will update the description, etc when I have made all the commits. 
2. Want to check if I am on the correct path and implementing all the necessary components. 

## Description

## Related Issue(s)

## Other information

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have run `yarn test` without getting any errors
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2024-07-31 12:32 UTC, YashBit commented
@cedoor I have created a DynamicCalculator trait which will works the same way but with the depth as a parameter now. This basically controls the loop. 

In -> packages/merkle-trees/src/incremental_merkle/tree.nr

Please let me know if this is the correct direction of implementation with a simple new modified trait that I have completed. 

After which I will focus on the MembershipProver, etc methods. Then write the Poseidon Hash tests.

2024-08-09 14:59 UTC, cedoor reviewed
@YashBit there's code which is not related to this PR (e.g. ecdh). I think you need to open a PR for the binary merkle tree by forking the main branch of zk-kit.noir.

2024-08-09 15:11 UTC, cedoor requested changes

2024-08-09 15:11 UTC, cedoor commented on packages/merkle-trees/src/incremental_merkle.nr
This file looks the same as: https://github.com/privacy-scaling-explorations/zk-kit.noir/blob/main/packages/merkle-trees/src/merkle.nr . I think you can re-use the same code. In the end what you should implement here is the same tree (binary merkle tree, the 'incremental' property is out of context here).

2024-08-09 15:11 UTC, cedoor commented on packages/merkle-trees/src/lib.nr
> +
This is also the same as the existing `trait MT_Creator`. I guess you can re-use the same code.

2024-08-09 15:16 UTC, cedoor commented
@YashBit 

>  1. Please let me know if this is the correct direction of implementation with a simple new modified trait that I have completed.

The trait seems to be fine, I added other comments for some files that are actually just a copy of the current Merkle tree. You should be able to re-use that code.
 
>  2. After which I will focus on the MembershipProver, etc methods. Then write the Poseidon Hash tests.
 
 Yes, those functions still need to be implemented I guess.
 
> For the tests, how would you like me to test the dynamic depth function? So I should create a tree (let's say of depth 4), and then calculate the results for depth 1, 2, 3?

Exactly, sounds like a good way to test them. Please, take a look at these tests here: https://github.com/privacy-scaling-explorations/zk-kit.circom/blob/326cef9fdb9a2f845b890cffea0594975768be1f/packages/binary-merkle-root/tests/binary-merkle-root.test.ts#L98. You should have the same tests in Noir here.

Also, be aware that this is not an incremental Merkle tree. It works as a general binary Merkle tree with an addition feature: dynamic depth, i.e. the ability to generate a proof with an arbitrary depth even if there's a maximum depth in the circuit (which must be static by design).

2024-08-12 10:13 UTC, signorecello commented
Converting to draft while not ready to merge

2024-08-23 13:41 UTC, sripwoud commented on package.json
> +    "@types/mocha": "^10",
are you planning to write some node tests for this too (with mocha) like in #8?
If not, we don't need these deps

2024-08-26 14:38 UTC, YashBit commented
@signorecello Please can you change this back from the draft? The core logic is complete, adding a few tests now.

2024-08-26 17:09 UTC, YashBit commented
@signorecello 

Could you please comment on the algorithm? Most of it should remain the same, it is just the calculate_root function in now a new trait called DynamicCalculator which should be able to handle the depth function dynamically.

Thank you again.

2024-08-30 12:04 UTC, sripwoud requested changes
@YashBit I think you need to [`rebase`](https://git-scm.com/docs/git-rebase) your branch on `main`. This PR shows up changes related to eg mocha dependencies while you added these in #8  already.  

And formatting CI check is still failing

2024-08-30 12:24 UTC, YashBit commented
@sripwoud I will make those changes.

I am mainly concerned with the logic of the incremental tree. That is the most important, since after that I will be done with unit the tests as well.

2024-09-02 14:40 UTC, signorecello commented
Hey @YashBit I don't understand the goal here. When you use this library in a circuit, you won't be able to pass anything other than an array into its `main` circuit.

I don't believe we should merge this PR without a `bin` circuit that would show its usage

2024-09-02 14:41 UTC, signorecello requested changes
Hey @YashBit I don't understand the goal here. When you use this library in a circuit, you won't be able to pass anything other than an array into its main circuit.

I don't believe we should merge this PR without a bin circuit that would show its usage

2024-09-02 15:04 UTC, cedoor commented
@YashBit can we close this PR in favor of https://github.com/privacy-scaling-explorations/zk-kit.noir/pull/16 ?

2024-09-02 15:09 UTC, YashBit commented
@cedoor Yes, please close this one!

2024-09-02 15:10 UTC, closed without merging